name: crypto
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - folium
  - plotly
  - cryptography
  - scipy
  - scikit-learn
  - h3-py
  - libpysal
  - esda
  - pointpats
  - seaborn
  - geopy